import AppKit

/// Reads the clipboard as completion context, opt-in.
///
/// Read at request time and never persisted, never logged. Bounded so a copied
/// document cannot crowd out the text the user is actually writing.
@MainActor
enum ClipboardContext {
    private static let limit = 400

    /// How long a copy stays relevant. Something copied an hour ago is not what
    /// the current sentence is about, and feeding it in on every model pass is
    /// noise the suggestion has to fight.
    private static let freshness: TimeInterval = 5 * 60

    /// The pasteboard conventions password managers use to mark a copied secret
    /// (nspasteboard.org). Honouring these is what actually keeps credentials
    /// out, which is why the shape of the string no longer has to carry it.
    private static let concealed = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
    private static let autoGenerated = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")

    /// Reading `changeCount` at first use means whatever was already on the
    /// clipboard when the app launched counts as unobserved, not as fresh.
    private static var lastChangeCount = NSPasteboard.general.changeCount
    private static var lastChangedAt: Date?

    /// The pasteboard is a parameter so tests can drive a named board instead
    /// of clobbering whatever the user has copied.
    static func current(from board: NSPasteboard = .general) -> String? {
        noteChange(on: board)

        // Only a recent copy is context. An unobserved one — present before
        // launch, or copied during a long silence — is not.
        guard let changedAt = lastChangedAt,
              Date().timeIntervalSince(changedAt) <= freshness else { return nil }

        let types = board.types ?? []
        guard !types.contains(concealed), !types.contains(autoGenerated) else { return nil }

        guard let raw = board.string(forType: .string) else { return nil }
        let trimmed = raw.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty, !looksLikeSecret(trimmed) else { return nil }
        return String(trimmed.prefix(limit))
    }

    /// Stamps when the clipboard last changed.
    ///
    /// The stamp is only as good as the polling: a copy made during a long
    /// silence is first seen here and dated now, so it is treated as newer than
    /// it is. That errs toward including context, which is the harmless
    /// direction, and the window above keeps it bounded either way.
    private static func noteChange(on board: NSPasteboard) {
        let count = board.changeCount
        guard count != lastChangeCount else { return }
        lastChangeCount = count
        lastChangedAt = Date()
    }

    /// `name@host.tld`: one "@" with something before it and a dotted domain
    /// after. A stricter question than "contains an @", which every credential
    /// with one in it also answered yes to.
    static func looksLikeEmailAddress(_ text: String) -> Bool {
        let parts = text.split(separator: "@", omittingEmptySubsequences: false)
        guard parts.count == 2, !parts[0].isEmpty else { return false }
        let domain = parts[1]
        guard let dot = domain.lastIndex(of: "."), dot != domain.startIndex else { return false }
        return domain[domain.index(after: dot)...].count >= 2
    }

    /// Fallback for managers that set no concealed flag. Internal rather than
    /// private so the table of cases can be tested directly.
    ///
    /// The rule this replaces — reject anything without whitespace — threw away
    /// what people actually copy before writing a reply: a name, a link, an
    /// address, an order number. It also passed a multi-word passphrase
    /// straight through, so it never bought the safety it cost.
    static func looksLikeSecret(_ text: String) -> Bool {
        // Issued tokens are the leak worth naming explicitly: several are all
        // lower case, so the entropy test below would let them past.
        let prefixes = ["sk-", "sk_", "pk_", "ghp_", "gho_", "github_pat_",
                        "xoxb-", "xoxp-", "AKIA", "ASIA", "AIza", "-----BEGIN"]
        if prefixes.contains(where: { text.hasPrefix($0) }) { return true }

        guard !text.contains(where: \.isWhitespace), text.count >= 12 else { return false }

        // Long unspaced strings that are not secrets: links, paths, addresses.
        //
        // Shape, not the mere presence of a character. Exempting anything that
        // contained a "/" or an "@" anywhere waved through every standard
        // base64 payload — "/" and "+" are two of its sixty-four characters —
        // which is precisely the string the entropy test below exists to catch.
        //
        // The cost is a bare relative path in mixed case with digits in it,
        // "Vendor/llama.xcframework/macos-arm64", now reading as a secret. That
        // is the right way round to be wrong: withholding it loses a line of
        // context, and this function is the fallback for password managers that
        // set no concealed flag.
        let lowered = text.lowercased()
        if lowered.contains("://") || lowered.hasPrefix("www.") { return false }
        if text.hasPrefix("/") || text.hasPrefix("~/") || text.hasPrefix("./") { return false }
        if looksLikeEmailAddress(text) { return false }

        // A generated credential mixes cases and adds digits or symbols. An
        // order number or a tracking code does not mix cases, and a word does
        // neither, so both survive.
        let hasLower = text.contains(where: \.isLowercase)
        let hasUpper = text.contains(where: \.isUppercase)
        let hasDigit = text.contains(where: \.isNumber)
        let hasSymbol = text.contains { $0.isASCII && !$0.isLetter && !$0.isNumber }
        return hasLower && hasUpper && (hasDigit || hasSymbol)
    }
}
