import AppKit
import Foundation

/// Ranked alternatives for one caret.
///
/// The promise is that asking for more suggestions gives *different* ones,
/// cheaply. Both halves are checked: that the candidates are distinct and each
/// usable on its own, and that the second costs a fraction of the first rather
/// than the same again — which is the whole reason they are generated by
/// forbidding openings against a resident prompt instead of by running the
/// model from scratch.

let prompts = [
    "Thanks for taking the time to",
    "I wanted to follow up on",
    "Apologies for the delay, I have been",
    "Just pushed the fix — can you",
]

var failures = 0
@MainActor func check(_ label: String, _ condition: Bool) {
    print("\(condition ? "PASS" : "FAIL") \(label)")
    if !condition { failures += 1 }
}

@MainActor
func run() async {
    guard let path = CommandLine.arguments.dropFirst().first else {
        print("usage: alternatives <model.gguf>"); exit(2)
    }
    let backend = LlamaBackend()
    await backend.load(path: path)
    guard await backend.status().isReady else { print("  load failed"); exit(1) }
    await backend.warmUp()

    var firstTotal = 0.0
    var restTotal = 0.0
    var withAlternatives = 0

    for before in prompts {
        let request = CompletionRequest(
            before: before, after: "", appName: "Mail", instructions: "",
            needsLeadingSpace: WordBoundary.caretEndsCompleteWord(before),
            maxWords: 6
        )

        var started = Date()
        let one = await backend.completions(request, count: 1)
        firstTotal += Date().timeIntervalSince(started)

        started = Date()
        let ranked = await backend.completions(request, count: 3)
        restTotal += Date().timeIntervalSince(started)

        guard let primary = ranked.first else {
            check("\(before): produced a suggestion", false); continue
        }
        check("\(before): one and three agree on the best", one.first == primary)
        let others = Array(ranked.dropFirst())
        print("  \"\(before)\"")
        print("     1. \(primary.debugDescription)")
        for (index, text) in others.enumerated() {
            print("     \(index + 2). \(text.debugDescription)")
        }

        // Not every prompt can offer more. Where the model is sure, every
        // attempt opens on the same word and the dedupe rightly keeps only
        // one; the count below is what catches the feature failing outright.
        if others.isEmpty { print("     (no distinct alternative — model was sure)") }
        withAlternatives += others.isEmpty ? 0 : 1
        check("\(before): none repeats the first", !others.contains(primary))
        check("\(before): none repeats another", Set(others).count == others.count)
        check("\(before): none is blank", others.allSatisfy {
            $0.contains(where: { $0.isLetter || $0.isNumber })
        })
        // Each has to open differently, or they are the same suggestion with a
        // different tail and there was no point offering them.
        let openings = ([primary] + others).map { $0.trimmingCharacters(in: .whitespaces).prefix(3) }
        check("\(before): each opens differently", Set(openings).count == openings.count)
    }

    check("most prompts offered an alternative", withAlternatives >= prompts.count - 1)

    // Three candidates against one. From scratch that would be three times the
    // work; against a resident prompt it should be well under.
    let ratio = restTotal / max(firstTotal, 0.001)
    print(String(format: "\n  one candidate %.0f ms · three candidates %.0f ms · ratio %.2f",
                 firstTotal * 1000, restTotal * 1000, ratio))
    check("three candidates cost well under three separate passes", ratio < 3.0)

    await backend.unload()
    print(failures == 0 ? "\nAlternatives verified." : "\n\(failures) FAILED")
    exit(failures == 0 ? 0 : 1)
}

await run()
